## Neural Network with 3 input

In [3]:
inputs = [2,3,4]
weights = [0.4,0.6,0.8] ##shows the importance of respective inputs
bias = 0.5
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

## Numpy Version
import numpy as np 
output = np.dot(inputs,weights) + bias
print(output)

6.3
6.3


## Neural Network with 4 inputs

In [6]:
inputs = [1,2,3,2.5]
weights = [0.2,0.4,0.8,0.1]
bias = 1.5
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(output)

import numpy as np 
output = np.dot(inputs,weights)+bias
print(output)

5.15
5.15


## Layers of Neurons

In [7]:
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,0.5,0.1],[0.4,0.3,0.8,0.4],[0.4,0.35,0.89,0.15]] ## Every neuron have its own sets of weights
bias_1 = 2
bias_2 = 3
bias_3 = 1.5
output = ((inputs[0]*weights[0][0] + inputs[1]*weights[0][1] + inputs[2]*weights[0][2]+ inputs[3]*weights[0][3]+ bias_1)+
          (inputs[0]*weights[1][0] + inputs[1]*weights[1][1] + inputs[2]*weights[1][2]+ inputs[3]*weights[1][3]+ bias_2)+
          (inputs[0]*weights[2][0] + inputs[1]*weights[2][1] + inputs[2]*weights[2][2]+ inputs[3]*weights[2][3]+ bias_3))
print(output)

import numpy as np 
result = np.dot(inputs,weights[0]) + bias_1
result +=np.dot(inputs,weights[1]) + bias_2
result+=np.dot(inputs,weights[2]) + bias_3
print(result)


18.595
18.595


In [1]:
inputs = [1,2,3,2.5]

weights = [[0.2,0.8,0.5,0.1],[0.4,0.3,0.8,0.4],[0.4,0.35,0.89,0.15]] ## Every neuron have its own sets of weights

bias = [2,3,1.5]

neuron_output = 0
output = []
for i in range (0 , len(weights)):
    for j in range(0,len(inputs)):
        neuron_output += (weights[i][j]*inputs[j] )
    neuron_output += bias[i]
    output.append(neuron_output)

output

[5.55, 12.95, 18.595]

In [10]:
import numpy as np
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,0.5,0.1],[0.4,0.3,0.8,0.4],[0.4,0.35,0.89,0.15]] ## Every neuron have its own sets of weights
bias = [2,3,1.5]

inputs_array = np.array(inputs)
weights_array = np.array(weights)
bias_array = np.array(bias)

output = np.dot(weights_array,inputs_array)+bias_array
print(output)

[5.55  7.4   5.645]


In [12]:
inputs = [[1.0, 2.0, 3.0, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

inputs_array = np.array(inputs)
weights_array = np.array(weights)
bias_array = np.array(bias)

result = np.dot(inputs_array,weights_array.T)+bias_array
print(result)

[[ 4.8    1.21   3.385]
 [ 8.9   -1.81   1.2  ]
 [ 1.41   1.051  1.026]]
