## Neural Network with 3 input

In [3]:
inputs = [2,3,4]
weights = [0.4,0.6,0.8] ##shows the importance of respective inputs
bias = 0.5
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

## Numpy Version
import numpy as np 
output = np.dot(inputs,weights) + bias
print(output)

6.3
6.3


## Neural Network with 4 inputs

In [6]:
inputs = [1,2,3,2.5]
weights = [0.2,0.4,0.8,0.1]
bias = 1.5
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(output)

import numpy as np 
output = np.dot(inputs,weights)+bias
print(output)

5.15
5.15


## Layers of Neurons

In [7]:
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,0.5,0.1],[0.4,0.3,0.8,0.4],[0.4,0.35,0.89,0.15]] ## Every neuron have its own sets of weights
bias_1 = 2
bias_2 = 3
bias_3 = 1.5
output = ((inputs[0]*weights[0][0] + inputs[1]*weights[0][1] + inputs[2]*weights[0][2]+ inputs[3]*weights[0][3]+ bias_1)+
          (inputs[0]*weights[1][0] + inputs[1]*weights[1][1] + inputs[2]*weights[1][2]+ inputs[3]*weights[1][3]+ bias_2)+
          (inputs[0]*weights[2][0] + inputs[1]*weights[2][1] + inputs[2]*weights[2][2]+ inputs[3]*weights[2][3]+ bias_3))
print(output)

import numpy as np 
result = np.dot(inputs,weights[0]) + bias_1
result +=np.dot(inputs,weights[1]) + bias_2
result+=np.dot(inputs,weights[2]) + bias_3
print(result)


18.595
18.595


In [1]:
inputs = [1,2,3,2.5]

weights = [[0.2,0.8,0.5,0.1],[0.4,0.3,0.8,0.4],[0.4,0.35,0.89,0.15]] ## Every neuron have its own sets of weights

bias = [2,3,1.5]

neuron_output = 0
output = []
for i in range (0 , len(weights)):
    for j in range(0,len(inputs)):
        neuron_output += (weights[i][j]*inputs[j] )
    neuron_output += bias[i]
    output.append(neuron_output)

output

[5.55, 12.95, 18.595]

In [10]:
import numpy as np
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,0.5,0.1],[0.4,0.3,0.8,0.4],[0.4,0.35,0.89,0.15]] ## Every neuron have its own sets of weights
bias = [2,3,1.5]

inputs_array = np.array(inputs)
weights_array = np.array(weights)
bias_array = np.array(bias)

output = np.dot(weights_array,inputs_array)+bias_array
print(output)

[5.55  7.4   5.645]


In [12]:
inputs = [[1.0, 2.0, 3.0, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

inputs_array = np.array(inputs)
weights_array = np.array(weights)
bias_array = np.array(bias)

result = np.dot(inputs_array,weights_array.T)+bias_array
print(result)

[[ 4.8    1.21   3.385]
 [ 8.9   -1.81   1.2  ]
 [ 1.41   1.051  1.026]]


## 2 Layer with Batches of Data

In [ ]:
import numpy as np

inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

# Calculate the output of the first layer
layer1_outputs = np.dot(inputs_array, weights_array.T) + biases_array  ## 4,3 * 3,4 = 3*3

# Calculate the output of the second layer
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array ## 3,3 * 3,3 = 3*3

print(layer2_outputs)


[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


## Dense Layer Class

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
class dense_layer :
    def __init__(self,n_input,neuron):
        self.weight = np.random.randn(n_input,neuron)
        self.bias = np.zeros((1,neuron))

    def forward(self,input):
        self.output = np.dot(input,self.weight)+self.bias
    
layer1 = dense_layer(2,3)
x,y = spiral_data(samples=100,classes=3)
output= layer1.forward(x)
print(output[:5])
        



[[ 0.          0.          0.        ]
 [ 0.02307935  0.01896055 -0.00961792]
 [ 0.05009951  0.03851381 -0.01655729]
 [ 0.08533785  0.05533896 -0.01143453]
 [ 0.11313757  0.07447607 -0.01697261]]


## One Neural Network Forward Pass

In [14]:
# Softmax activation
class Activation_Softmax:
 # Forward pass
 def forward(self, inputs):
 # Get unnormalized probabilities
  exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
 # Normalize them for each sample
  probabilities = exp_values / np.sum(exp_values, axis=1,keepdims=True)
  self.output = probabilities

In [15]:
# ReLU activation
class Activation_ReLU:
 # Forward pass
 def forward(self, inputs):
 # Calculate output values from input
  self.output = np.maximum(0, inputs)

In [16]:
# Create dataset
X, y = spiral_data(samples=100, classes=3)
# Create Dense layer with 2 input features and 3 output values
dense1 = dense_layer(2, 3)
# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()
# Create second Dense layer with 3 input features (as we take output
# of previous layer here) and 3 output values
dense2 = dense_layer(3, 3)
# Create Softmax activation (to be used with Dense layer):
activation2 = Activation_Softmax()

# Make a forward pass of our training data through this layer
dense1.forward(X)

# Make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)
# Make a forward pass through second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)
# Make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)
# Let's see output of the first few samples:
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]]
