In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

class dense_layer:
    def __init__(self,n_input,neuron):
        self.weight = 0.1*np.random.randn(n_input,neuron)
        self.biases = np.zeros((1,neuron))
        
    def forward(self,input):
        output = np.dot(input,self.weight)+self.biases
        return output
    
class Relu:
    def forward(self,input):
            return np.maximum(0,input)

class Softmax:
    def forward(self,input):
        exp = np.exp(input - np.max(input, axis=1,keepdims=True))
        output = exp/np.sum(exp,axis=1,keepdims=True) 
        return output

x,y = spiral_data(classes=3,samples=100)

first_layer = dense_layer(2,3)
output1 = first_layer.forward(x)

activation = Relu()
activation_result = activation.forward(output1)

second_layer = dense_layer(3,3)
output2 = second_layer.forward(activation_result)

SM = Softmax()
final_result = SM.forward(output2)

print(final_result[:5])
len(final_result.shape)


[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


300

In [ ]:
class CROSS_ENTROPY:
    def forward(self,target,input):
        samples = len(input)
        clipping = np.clip(input,1e-7,1 - 1e-7)
        if len(input.shape) == 1:
            confidence = clipping[range(samples),target]
            
        else:
            confidence_matrix = clipping * target
            confidence = np.sum(confidence_matrix,keepdims=True,axis=1)
        
        loss = -np.log(confidence)
        
        return loss
            